CREATE TABLE IF NOT EXISTS mcp_gateway (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gateway_id VARCHAR(64) NOT NULL,
    gateway_name VARCHAR(128) NOT NULL,
    gateway_desc VARCHAR(512),
    version VARCHAR(16),
    auth TINYINT DEFAULT 0,
    status TINYINT DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_mcp_gateway_gateway_id ON mcp_gateway (gateway_id);

CREATE TABLE IF NOT EXISTS mcp_gateway_auth (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gateway_id VARCHAR(64) NOT NULL,
    api_key VARCHAR(128),
    rate_limit INT DEFAULT 1000,
    expire_time TIMESTAMP,
    status TINYINT DEFAULT 1 NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_mcp_gateway_auth_api_key ON mcp_gateway_auth (api_key);

CREATE TABLE IF NOT EXISTS mcp_gateway_tool (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gateway_id VARCHAR(64) NOT NULL,
    tool_id BIGINT NOT NULL,
    tool_name VARCHAR(128) NOT NULL,
    tool_type VARCHAR(32) NOT NULL DEFAULT 'function',
    tool_description VARCHAR(512) NOT NULL,
    tool_version VARCHAR(16) NOT NULL,
    protocol_id BIGINT NOT NULL,
    protocol_type VARCHAR(8) NOT NULL DEFAULT 'http',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_mcp_gateway_tool_name ON mcp_gateway_tool (gateway_id, tool_name);
CREATE UNIQUE INDEX IF NOT EXISTS uq_mcp_gateway_tool_id ON mcp_gateway_tool (tool_id);

CREATE TABLE IF NOT EXISTS mcp_protocol_http (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    protocol_id BIGINT NOT NULL,
    http_url VARCHAR(512) NOT NULL,
    http_method VARCHAR(16) NOT NULL DEFAULT 'post',
    http_headers CLOB,
    timeout INT DEFAULT 30000,
    retry_times TINYINT DEFAULT 0,
    status TINYINT DEFAULT 1 NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_mcp_protocol_http_protocol_id ON mcp_protocol_http (protocol_id);

CREATE TABLE IF NOT EXISTS mcp_protocol_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    protocol_id BIGINT NOT NULL,
    mapping_type VARCHAR(32) NOT NULL,
    parent_path VARCHAR(256),
    field_name VARCHAR(128) NOT NULL,
    mcp_path VARCHAR(256) NOT NULL,
    mcp_type VARCHAR(32) NOT NULL,
    mcp_desc VARCHAR(512),
    is_required TINYINT DEFAULT 0 NOT NULL,
    sort_order INT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_mcp_protocol_mapping_protocol_id ON mcp_protocol_mapping (protocol_id);

INSERT INTO mcp_gateway (gateway_id, gateway_name, gateway_desc, version, auth, status, create_time, update_time)
SELECT 'gateway_001', 'MCP Gateway', 'Default gateway config', '1.0.0', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM mcp_gateway WHERE gateway_id = 'gateway_001');

INSERT INTO mcp_gateway_auth (gateway_id, api_key, rate_limit, expire_time, status, create_time, update_time)
SELECT 'gateway_001', 'gw-demo-admin-key', 3600, DATEADD('DAY', 3650, CURRENT_TIMESTAMP), 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM mcp_gateway_auth WHERE gateway_id = 'gateway_001');

INSERT INTO mcp_protocol_http (protocol_id, http_url, http_method, http_headers, timeout, retry_times, status, create_time, update_time)
SELECT 1001, 'https://weather.example.com/mcp', 'post', '{"Content-Type":"application/json"}', 30000, 3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM mcp_protocol_http WHERE protocol_id = 1001);

INSERT INTO mcp_gateway_tool (gateway_id, tool_id, tool_name, tool_type, tool_description, tool_version, protocol_id, protocol_type, create_time, update_time)
SELECT 'gateway_001', 5001, 'forecast', 'function', 'Return mock forecast', '1.0.0', 1001, 'http', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM mcp_gateway_tool WHERE tool_id = 5001);

INSERT INTO mcp_protocol_mapping (protocol_id, mapping_type, parent_path, field_name, mcp_path, mcp_type, mcp_desc, is_required, sort_order, create_time, update_time)
SELECT 1001, 'request', NULL, 'city', 'city', 'string', 'City name', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM mcp_protocol_mapping WHERE protocol_id = 1001 AND mcp_path = 'city');

INSERT INTO mcp_protocol_mapping (protocol_id, mapping_type, parent_path, field_name, mcp_path, mcp_type, mcp_desc, is_required, sort_order, create_time, update_time)
SELECT 1001, 'request', NULL, 'days', 'days', 'integer', 'Forecast days', 0, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM mcp_protocol_mapping WHERE protocol_id = 1001 AND mcp_path = 'days');
